### PR TITLE
fix: Completion insertion misaligned under CJK langs & Completion ref…

### LINKED ISSUE #679: Unable to fetch refs completion source after  3.15.8
### 🐛 Describe the bug

After v3.15.8, it is unable to fetch refs completion source when typing after `[[` Image

After rolling back before commit 44060ccca31f1c67e89f08bcc663a7e318667e5d, or just change the [line](https://github.com/obsidian-nvim/obsidian.nvim/blob/44060ccca31f1c67e89f08bcc663a7e318667e5d/lua/obsidian/path.lua#L441) 
`local root = api.resolve_workspace_dir()`
 to  `local root = api.find_workspace(tostring(self)).root`
then it is able to fetch the source again
Image

### Config

```
...
 workspaces = {
    {
      name = "Notes",
      path = vim.fn.expand("~") .. "/Notes",
    }
  },
  completion = (function()
    local has_nvim_cmp, _ = pcall(require, "cmp")
    local has_blink = pcall(require, "blink.cmp")
    return {
      nvim_cmp = has_nvim_cmp and not has_blink,
      blink = has_blink,
      min_chars = 2,
      match_case = true,
      create_new = true,
    }
  end)(),
...

```

### Environment

- ✅ OK neovim >= 0.11 (0.12.0-dev+ga945686444)

[Version] ~
- ✅ OK obsidian.nvim v3.15.8 (8ab5bb9b58edafce994f8c8e709d82c37e3257e0)

[Environment] ~
- ✅ OK operating system: Linux

[Config] ~
- ✅ OK 
- 
[Pickers] ~
- ✅ OK snacks.nvim

[Completion] ~
- ✅ OK blink.cmp:

### PR DESCRIPTION
**Pull request by CaeChao**
What does the PR do?
should fix #679 and #671

## PR Checklist

- [x] The PR contains a description of the changes
- [x] I read the [CONTRIBUTING.md] file
- [x] The `CHANGELOG.md` is updated
- [ ] The changes are documented in the `README.md` file
- [x] The code complies with `make chores` (for style, lint, types, and tests)

### CODE REVIEW

File: lua/obsidian/path.lua [hunk 1]
```diff
@@ -439,14 +439,14 @@ Path.vault_relative_path = function(self, opts)
 
   local api = require "obsidian.api"
 
-  local root = api.resolve_workspace_dir()
+  local ws = api.find_workspace(tostring(self)) or Obsidian.workspace
```
Comment (neo451) [inline lua/obsidian/path.lua]: the `resolve_workspace_dir` literally do the rolled back thing, could you help find out why it is not working on your side, instead of just rollback

Comment (CaeChao) [reply lua/obsidian/path.lua]:
```

---@param path string|obsidian.Path|?
---@return obsidian.Path workspace_root
M.resolve_workspace_dir = function(path)
  local ws
  if vim.b.obsidian_buffer then
    ws = M.find_workspace(path or vim.api.nvim_buf_get_name(0))
  end
  if ws then
    return ws.root
  else
    return Obsidian.workspace.root
  end
end
```
also changing the function into something like this, yes

Comment (neo451) [reply lua/obsidian/path.lua]:
```suggestion
---@param path string|obsidian.Path|?
---@return obsidian.Path workspace_root
M.resolve_workspace_dir = function(path)
  local ws
  local buf = vim.api.nvim_get_current_buf()
  if path then
    ws = M.find_workspace(path)
  elseif vim.b[buf].obsidian_buffer = true then
    ws = M.find_workspace(vim.api.nvim_buf_get_name(buf))
  end
  if ws then
    return ws.root
  else
    return Obsidian.workspace.root
  end
end
```

I think this will work?
